In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5]

In [3]:
arr = np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
arr2d=[[1,2,3],[4,5,6]]
arr2=np.array(arr2d)

In [7]:
arr2.shape

(2, 3)

In [8]:
arr3=np.array([1,2,3,4,5])

In [9]:
arr3.shape

(5,)

In [10]:
print(arr3)

[1 2 3 4 5]


In [11]:
print(my_list)

[1, 2, 3, 4, 5]


In [12]:
arr2.shape


(2, 3)

In [13]:
arr.size

5

In [14]:
arr.dtype

dtype('int32')

In [15]:
print(arr[1:3])

[2 3]


In [16]:
print(arr)

[1 2 3 4 5]


In [17]:
for i in range(0,4):
    print(arr[i],end=" " )

1 2 3 4 

In [18]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
# printing 
for i in mat:
    print (i,end=" ")

[1 2 3] [4 5 6] [7 8 9] 

In [20]:
mat.shape

(3, 3)

In [21]:
arr.reshape(5,-1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
arr.std()

1.4142135623730951

In [23]:
arr.sum()

15

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
print(np.random.rand(1,3))

[[0.03313481 0.13986323 0.76193109]]


In [26]:
np.random.poisson(lam=3,size=10)

array([1, 2, 5, 5, 4, 6, 5, 1, 2, 5])

In [29]:
# pandas

In [30]:
import pandas as pd

In [45]:
s=pd.Series([1,2,3],index=['A','B','C'])
print(s)

A    1
B    2
C    3
dtype: int64


In [54]:
print(s.values,'\n',
s.index,'\n',
s.dtype)

[1 2 3] 
 Index(['A', 'B', 'C'], dtype='object') 
 int64


In [70]:
data = {
  "name": ["kk", "mm", "nn", "aa", "bb", "cc", "dd", "ee", "ff", "gg", "hh", "ii", "jj", "ll", "oo"],
  "age":  [18, 19, 20, 21, 22, 18, 19, 20, 21, 22, 23, 19, 20, 21, 22],
  "score":[80, 90,100, 75, 88, 92, 67, 85, 78, 91, 95, 82, 89, 76, 84]
}

df=pd.DataFrame(data,index=np.arange(1,16))
print(df)

   name  age  score
1    kk   18     80
2    mm   19     90
3    nn   20    100
4    aa   21     75
5    bb   22     88
6    cc   18     92
7    dd   19     67
8    ee   20     85
9    ff   21     78
10   gg   22     91
11   hh   23     95
12   ii   19     82
13   jj   20     89
14   ll   21     76
15   oo   22     84


In [71]:
df.head()

name  age  score
1   kk   18     80
2   mm   19     90
3   nn   20    100
4   aa   21     75
5   bb   22     88

In [74]:
type(df)

pandas.core.frame.DataFrame

In [83]:
df2=pd.DataFrame(data,columns=['name','age'])
print(df2.head())

  name  age
0   kk   18
1   mm   19
2   nn   20
3   aa   21
4   bb   22


In [85]:
df.loc[1]

name     kk
age      18
score    80
Name: 1, dtype: object

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 1 to 15
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    15 non-null     object
 1   age     15 non-null     int64 
 2   score   15 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 848.0+ bytes


In [104]:
df.loc[1:12,['name','age']]

name  age
1    kk   18
2    mm   19
3    nn   20
4    aa   21
5    bb   22
6    cc   18
7    dd   19
8    ee   20
9    ff   21
10   gg   22
11   hh   23
12   ii   19

In [112]:
df.iloc[0:10,0:2]

name  age
1    kk   18
2    mm   19
3    nn   20
4    aa   21
5    bb   22
6    cc   18
7    dd   19
8    ee   20
9    ff   21
10   gg   22

In [113]:
# converting dataframes into arrays
#method 1
df.values  

array([['kk', 18, 80],
       ['mm', 19, 90],
       ['nn', 20, 100],
       ['aa', 21, 75],
       ['bb', 22, 88],
       ['cc', 18, 92],
       ['dd', 19, 67],
       ['ee', 20, 85],
       ['ff', 21, 78],
       ['gg', 22, 91],
       ['hh', 23, 95],
       ['ii', 19, 82],
       ['jj', 20, 89],
       ['ll', 21, 76],
       ['oo', 22, 84]], dtype=object)

In [117]:
#method 2
df.to_numpy()

array([['kk', 18, 80],
       ['mm', 19, 90],
       ['nn', 20, 100],
       ['aa', 21, 75],
       ['bb', 22, 88],
       ['cc', 18, 92],
       ['dd', 19, 67],
       ['ee', 20, 85],
       ['ff', 21, 78],
       ['gg', 22, 91],
       ['hh', 23, 95],
       ['ii', 19, 82],
       ['jj', 20, 89],
       ['ll', 21, 76],
       ['oo', 22, 84]], dtype=object)

In [120]:
df.isnull()

name    age  score
1   False  False  False
2   False  False  False
3   False  False  False
4   False  False  False
5   False  False  False
6   False  False  False
7   False  False  False
8   False  False  False
9   False  False  False
10  False  False  False
11  False  False  False
12  False  False  False
13  False  False  False
14  False  False  False
15  False  False  False

In [121]:
df['name'].value_counts()

name
kk    1
mm    1
nn    1
aa    1
bb    1
cc    1
dd    1
ee    1
ff    1
gg    1
hh    1
ii    1
jj    1
ll    1
oo    1
Name: count, dtype: int64