In [1]:
# X_train , y_train 
# X_test , y_test

In [2]:
import numpy as np
X=np.array([1,2,3,4,5])
y=np.array([2,4,6,8,10])

In [3]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,y_train,X_test,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [12]:
X_train

array([5, 3, 1, 4])

In [13]:
y_train

array([2])

In [14]:
X_test

array([10,  6,  2,  8])

In [15]:
y_test

array([4])